### ISSUE TITLE
UnexpectedText when demangling symbol

### ISSUE THREAD

**Issue by geNAZt** [gimli-rs/cpp_demangle#219] opened 2020-11-22 12:47 UTC
When i try to demangle `_ZNKSt8__detail15_Hash_code_baseIPKN8JsonUtil32JsonSchemaNodeChildSchemaOptionsINS1_14JsonParseStateINS3_INS3_INS3_INS3_INS3_INS3_INS1_10EmptyClassEN14FeatureLoading23FeatureRootParseContextEEENS5_21ConcreteFeatureHolderI18VanillaTreeFeatureEEEE13MegaTreeTrunkEESC_EESC_EE16SimpleTreeCanopyEESG_EEN10TreeHelper20AttachableDecoration15GrowthDirectionEEESO_NS_9_IdentityESt4hashISO_ENS_18_Mod_range_hashingENS_20_Default_ranged_hashELb0EE15_M_bucket_indexEPKNS_10_Hash_nodeISO_Lb0EEEm` i get a UnexpectedText error. Demangling with https://github.com/ianlancetaylor/demangle shows no error on that.

**Comment by khuey** [comment] 2020-11-22 15:30
This symbol exceeds our default parsing recursion limit of 64. If that gets bumped up far enough it demangles fine and to the same output as c++filt/llvm-cxxfilt. I'm going to close this as a duplicate of #207.

**Closed by khuey** 2020-11-22 15:30 UTC
